version: '3'

services:
  app:
    build: .
    command: npm start
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    links:
      - db
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
